# hook_add	プラグインが dein.vim によって追加されたとき
# hook_source	プラグインが読み込まれる直前
# hook_post_source	プラグインが読み込まれた直後
# hook_post_update	プラグインが更新された直後

[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
" fzfコマンドのprefixを設定
let g:fzf_command_prefix = 'Fzf'

" bufferを表示
nnoremap <silent> ,B :<C-u>:FzfBuffers<CR>
" Commandを表示
nnoremap <silent> ,C :<C-u>:FzfCommands<CR>
" Filesを表示
nnoremap <silent> ,f :<C-u>:FzfFiles<CR>
" Helpを表示
nnoremap <silent> ,H :<C-u>:FzfHelptags<CR>
" ファイル履歴を表示
nnoremap <silent> ,r :<C-u>:FzfHistory<CR>
" コマンド履歴を表示
nnoremap <silent> ,R :<C-u>:FzfHistory:<CR>
cnoremap <C-r> :<C-u>:FzfHistory:<CR>
" Windowを表示
nnoremap <silent> ,w :<C-u>:FzfWindows<CR>
'''

[[plugins]]
repo = 'nanotee/zoxide.vim'
hook_add = '''
" cdの際にdirectoryのスコアを増やす
let g:zoxide_hook = 'pwd'
" zoxideを起動
cnoremap zz :i<CR>
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'lambdalisue/gin.vim'

# ファイラー
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
" 隠しファイルも表示する
let g:fern#default_hidden = 1

" ,eでdrawerを開くまたはフォーカスする
noremap <silent> ,e :<C-u>:Fern . -drawer -reveal=%<CR>
" ,bでdrawerを開閉する
noremap <silent> ,b :<C-u>:Fern . -drawer -reveal=% -toggle<CR>
'''

# エディター関連
[[plugins]]
repo = 'jiangmiao/auto-pairs'
hook_add = '''
" auto-pairsの削除を無効
let g:AutoPairsMapBS = 0
" auto-pairsのスペースを無効
let g:AutoPairsMapSpace = 0
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

## コメントアウト
[[plugins]]
repo = 'tpope/vim-commentary'

# markdown
[[plugins]]
repo = 'ksudate/prev-md.vim'
