autocomplete = true
breaking_changes = false
issues = false
emoji = false
sign = false

[[commit_types]]
name = "feat"
description = "新機能"

[[commit_types]]
name = "chore"
description = "その他(雑多な対応)"

[[commit_types]]
name = "fix"
description = "バグ修正"

[[commit_types]]
name = "refactor"
description = "リファクタリングのための変更(機能追加やバグ修正を含まない)"

[[commit_types]]
name = "wip"
description = "作業途中"

[[commit_types]]
name = "test"
description = "テスト"

